// Version04/Modulo06/React/miprimeraaplicacion/src/components/Footer.js
const Footer = () => {
    return(
      <footer className="p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
        <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2022 Pepito Perez. Derechos reservados.
        </span>
      </footer>
    )
  }
  
  export default Footer;

// Version04/Modulo06/Vue/miprimeraaplicacion/src/components/FooterComponent.vue
<template>
  <v-footer dark padless>
    <v-card class="flex" flat>
      <v-card-text class="py-2 white--text text-center">
        <strong>Hecho Con Amor por {{owner}}</strong>
      </v-card-text>
    </v-card>
  </v-footer>
</template>

<script>
export default {
  name: "FooterComponent",
  data: () => ({
      owner: 'Pepito Perez'
  })
};
</script>
