// Version04/Modulo06/React/miprimeraaplicacion/src/components/vehicles/Vehicles.js
import { useState, useEffect } from "react";
import { getVehicles } from "../../services/Vehicles";
import Vehicle from "./Vehicle";

const Vehicles = () => {
  const [isLoading, setIsLoding] = useState(true);
  const [vehicles, setVehicles] = useState([]);

  useEffect(() => {
    getVehicles().then((response) => {
      setVehicles(response);
      setIsLoding(false);
    });
  }, []);

  return (
    <>
      <div className="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
        {isLoading && vehicles.length === 0 && <p>Cargando Información...</p>}
        {!isLoading && vehicles.map((vehicleTemporal) => (
          <Vehicle vehicle={vehicleTemporal} key={vehicleTemporal.id} />
        ))}
      </div>
    </>
  );
};

export default Vehicles;

// Version04/Modulo06/Vue/miprimeraaplicacion/src/components/vehicle/VehiclesComponent.vue
<template>
  <v-container>
    <h1 v-if="loading">Cargando...</h1>
    <ul v-else>
      <div v-for="vehicle in vehicles" :key="vehicle.id">
        <VehicleComponent :data="vehicle" />
      </div>
    </ul>
  </v-container>
</template>
<script>
import VehicleComponent from "./VehicleComponent";
import { getVehicles } from "../../services/Vehiculos";

export default {
  name: "VehiclesComponent",
  data: () => ({
    vehicles: [],
    loading: true,
  }),
  components: {
    VehicleComponent
  },
  mounted() {
    getVehicles().then((response) => {
      this.vehicles = response;
      this.loading = false;
    });
  }
};
</script>
